### ISSUE TITLE
FuelCell test outputs 800 MB out.osw file

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-resources#34]
The out.osw bloats to about 800 MB, due to the eplusout_err key, there is this warning being thrown 7,800,240 times 

    ** Warning ** CalcFuelCellGeneratorModel: Regula falsi problem, flag = -2, check signs, all positive'

Need to investigate whether this is an E+ problem or a test problem.

 (Perhaps also raises the question of whether storing raw eplusout_err messages is a good idea)

**Comment by jmarrec** [comment]
Thrown here: https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/FuelCellElectricGenerator.cc#L1646

**Comment by brianlball** [comment]
its an E+ problem with the Fuel Cell model.  We have Brent on subcontract looking at it for the EDC project.
