### ISSUE TITLE
Add OSM test for ITE once 2.7.2 is out

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-resources#65]
This is a reminder to add a matching OSM test for PR #63 which still has `PendingOSM` label. I checked that in 2.7.1 the ITE object isn't available, but should be in 2.7.2

**Comment by KaiyuSun** [comment]
@jmarrec @macumber   [https://github.com/NREL/OpenStudio/releases/tag/v2.7.2-update_measure_tester1](url) is this supposed to be the 2.7.2 release? I checked the source code, it doesn't include the ITE object.

**Comment by jmarrec** [comment]
This probably just a test package. develop is still as 2.7.2, and does include the ITE, so it's going to be in 2.7.2 official.

**Comment by jmarrec** [comment]
Fixed by #63
