### ISSUE TITLE
`test_schedule_file_rb` fails with windows installer

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-resources#81]
Looks like the new E+ looks for the schedulefile.csv in a new `generated_files` folder, but OS is copying this file to `files`?

**Comment by macumber** [comment]
This is the related change in Workflow gem, https://github.com/NREL/OpenStudio-workflow-gem/commit/49ae9114542f1feeeb19a3686bd406b2db8f7d10

You'll want to make sure you are using a newer version of workflow gem in the tests, basically it creates a generated_files directory and adds it to the front of the files path when running an OSW.  Files added by ExternalFile are copied to the first directory in the files path, the path is converted to absolute when translated to E+.  E+ has no idea of generated_files, it just uses the path given to it.

**Comment by jmarrec** [comment]
I don't really understand the rationale for adding a new `generated_files` directory. Isn't the `files` good enough?

As far as I can tell, the first folder defined here determines where the files coming from  `ExternalFile`, `ForwardTranslateScheduleFixedInterval` (when translatetoScheduleFile() = true`) or `ApplyMeasuresNow` will end up in:

https://github.com/NREL/OpenStudio/blob/21285b9a20fa3ce57b7dfecc28f3c20291c9d7bc/openstudiocore/src/utilities/filetypes/WorkflowJSON.cpp#L446:L451

**Comment by jmarrec** [comment]
What happens is that we (=what `model_tests.rb` does) run:
* `openstudio schedule_file.rb` workflow gem isn't there, so `ExternalFile` finds `absoluteFilePaths[0] = "xxxx/files/` (and the ExternalFile object itself just references the name of the `schedulefile.csv`, no indication on path whatsoever) created by the script placed it in `files/schedule_file.csv`
* Then it runs `openstudio -w in.osw`, at which point we do have the workflow-gem loaded so `absoluteFilePaths[0] = "xxxx/generated_files/"` during `ForwardTranslateScheduleFile` so that's what ends up in the IDF, so E+ can't find it...

I'm not sure how to resolve this issue really, I guess I don't understand the workflow-gem enough nor what was tried to be achieved. Is it that files from API itself should go to `files/` but any generated by a measure at run time should go to `generated_files` instead?

**Comment by macumber** [comment]
`generated_files` is trying to fix the case where users are adding `files` paths pointing to directories in their measures or other shared directories.  This is useful when you want to read shared resources.  But as soon as you start writing in those directories, multiple OSW files start stepping on each other.  The idea was to create a directory unique to each OSW when WorkflowGem run starts, this is safe to write to.  But as you pointed out, this directory does not exist before you start the run.

This suggests to me that we need to push this code somewhere deeper than the workflow-gem.  One idea would be to add `writeableFilesDirs` or something to the `WorkflowJSON` class.  Then the `ExternalFIle` object would write to the first writeable file dir, not just the first files dir.  `ExternalFile` could create a writeable file dir if none exists.  We'd need to decide how to detect which file dirs are safe to write to.  Maybe something like they are nested underneath the run dir?

**Comment by macumber** [comment]
You could add a writeable file path to the models WorkflowJSON in the code that creates the model, but that seems pretty ugly, i think WorkflowJSON should do this for you

Related to https://github.com/NREL/OpenStudio/issues/3609

**Comment by macumber** [comment]
I believe that what might be happening is that at model creation time, the model's WorkflowJSON does not include any explicit file dirs so is uses a default one.  At OSW run time, the generated_files dir is added explicitly to the OSW, in that case WorkflowJSON forgets about the defaulted file dir used implicitly.  This is why the CSV file can't be found

**Comment by jmarrec** [comment]
Yeah that's what I said in https://github.com/NREL/OpenStudio-resources/issues/81#issuecomment-533511221 though perhaps that wasn't clear. I fixed it in https://github.com/NREL/OpenStudio/commit/356004ce08cb49f7e18d9a820745637dd444e2fd which I think is a valid solution.

**Comment by jmarrec** [comment]
@joseph-robertson could you try agian with 2.9.0 (or current develop) on windows please? It should be fixed.

**Comment by jmarrec** [comment]
Tested on windows with 2.9.0 official.

```
# Running tests with run options -n test_schedule_file_rb --seed 33952:
.
Finished tests in 52.739247s, 0.0190 tests/s, 0.0379 assertions/s.
1 tests, 2 assertions, 0 failures, 0 errors, 0 skips
```
